# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
set -g default-command "${SHELL}"

# Fix colors for Neovim inside tmux
set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm-256color:Tc"

# Remap split panes to something easier to remember
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Don't rename windows automatically
set-option -g allow-rename off

